---
- name: Install requirements
  dnf:
    name:
      - epel-release
    state: present
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: Get gpg key for php repo
  rpm_key:
    state: present
    key: https://rpms.remirepo.net/enterprise/9/RPM-GPG-KEY-remi

- name: Install php repo
  dnf:
    name:
      - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    state: present
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: Install php
  dnf:
    name:
      - '@php:remi-{{ php_version }}'
    state: present
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: Install php drivers
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - php-fpm
    - php-common
    - php-mysql
    - php-xml
    - php-xmlrpc
    - php-curl
    - php-gd
    - php-imagick
    - php-cli
    - php-imap
    - php-mbstring
    - php-opcache
    - php-redis
    - php-soap
    - php-zip
  register: result
  until: result is not failed
  retries: 5
  delay: 5

- name: Start php fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: Set PHP user
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^user"
    line: "user = {{ web_user }}"
    state: present
  notify: restart php

- name: comment acl user PHP user
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^listen\\.acl_users = apache,nginx"
    line: ";listen.acl_users = apache,nginx"
    state: present
  notify: restart php

- name: Set PHP group
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^group"
    line: "group = {{ web_user }}"
    state: present
  notify: restart php

- name: Set PHP listen owner
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^listen\\.owner"
    line: "listen.owner = {{ web_user }}"
    state: present
  notify: restart php

- name: Set PHP listen group
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: "^listen\\.group"
    line: "listen.group = {{ web_user }}"
    state: present
  notify: restart php

- name: Set PHP upload max filesize
  lineinfile:
    dest: /etc/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 128M"
    state: present
  notify: reload php

- name: Set PHP post max filesize
  lineinfile:
    dest: /etc/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 128M"
    state: present
  notify: reload php

- name: Set PHP post max filesize
  lineinfile:
    dest: /etc/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 128M"
    state: present
  notify: reload php
